name: Trivy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Trivy - Misconfiguration table
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'table'
          severity: 'CRITICAL,HIGH,MEDIUM'

      - name: Run Trivy in Config mode to generate SARIF
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'sarif'
          output: 'trivy-results.sarif'
      
      - name: Upload Trivy Scan results to GH Security
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'